import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { CheckCircle2, Copy, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { categoryLabels, planById } from '../data/plans'
import { db } from '../lib/firebase'

export default function Checkout(){
 const {planId}=useParams(); const plan=planById(planId||''); const {user,login}=useAuth(); const nav=useNavigate(); const [loading,setLoading]=useState(false); const [error,setError]=useState('')
 if(!plan) return <Navigate to="/plans" replace/> 
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); if(!user){await login();return} setLoading(true);setError(''); const fd=new FormData(e.currentTarget)
  try{const order={userId:user.uid,userName:user.displayName||'',userEmail:user.email||'',userPhoto:user.photoURL||'',planId:plan!.id,category:plan!.category,planName:plan!.name,amount:plan!.price||0,payerName:String(fd.get('payerName')),transactionId:String(fd.get('transactionId')),serverName:String(fd.get('serverName')),deliveryEmail:String(fd.get('deliveryEmail')),discordTicket:String(fd.get('discordTicket')||''),status:'pending',createdAt:serverTimestamp()}; const ref=await addDoc(collection(db,'orders'),order); const token=await user.getIdToken(); const api=import.meta.env.VITE_ORDER_API_URL; if(api){await fetch(`${api}/order`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${token}`},body:JSON.stringify({...order,orderId:ref.id,createdAt:new Date().toISOString()})})} nav(`/order-success/${ref.id}`)}catch(err:any){setError(err?.message||'Could not submit order. Check Firebase configuration and rules.')}finally{setLoading(false)}}
 return <section className="section top-space"><div className="container checkout-grid"><div><div className="section-heading left"><span>Secure Checkout</span><h1>{plan.name}</h1><p>{categoryLabels[plan.category]} · {plan.price!=null?`₹${plan.price}/${plan.period}`:'Reward plan'}</p></div><form className="form-card" onSubmit={submit}>{!user&&<div className="login-gate"><ShieldCheck/><div><strong>Google sign-in required</strong><p>Your account links this order to your dashboard.</p></div><button type="button" className="primary-btn small" onClick={login}>Continue with Google</button></div>}<div className="form-grid"><label>Payer name<input required name="payerName" placeholder="Name used for payment"/></label><label>Transaction ID<input required name="transactionId" placeholder="UPI transaction/reference ID"/></label><label>Server / service name<input required name="serverName" placeholder="Example: AG Survival"/></label><label>Delivery email<input required type="email" name="deliveryEmail" defaultValue={user?.email||''}/></label><label className="full-col">Discord ticket number or name (optional)<input name="discordTicket" placeholder="Example: ticket-1042"/></label></div>{error&&<p className="error">{error}</p>}<button disabled={loading} className="primary-btn full" type="submit">{loading?'Submitting...':'Submit payment details'}</button></form></div><aside className="payment-card"><h3>Pay using UPI</h3><img src="/assets/payment-qr.png" onError={(e)=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/><div className="qr-placeholder">Replace <code>public/assets/payment-qr.png</code> with your QR image.</div><button className="upi-copy" onClick={()=>navigator.clipboard.writeText(import.meta.env.VITE_UPI_ID||'replace-me@upi')}><span>{import.meta.env.VITE_UPI_ID||'replace-me@upi'}</span><Copy size={16}/></button><div className="payment-steps"><p><CheckCircle2/> Pay the exact amount.</p><p><CheckCircle2/> Copy the transaction ID.</p><p><CheckCircle2/> Submit the form for verification.</p></div></aside></div></section>
}
