import { ArrowRight, Gauge, Headphones, LockKeyhole, Server, ShieldCheck, Sparkles, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'

export default function Home(){return <>
 <section className="hero"><div className="hero-glow"></div><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={16}/> Premium hosting for ambitious communities</span><h1>Power your world with <span>AG Cloud</span></h1><p>Game servers, VPS, bot hosting and domains with high-performance infrastructure, low Asia latency and human support.</p><div className="hero-actions"><Link className="primary-btn" to="/plans">Explore Plans <ArrowRight size={18}/></Link><a className="secondary-btn" href={import.meta.env.VITE_DISCORD_INVITE_URL||'#'} target="_blank">Join Discord</a></div><div className="trust-row"><span>99.9% uptime</span><span>24/7 runtime</span><span>Fast deployment</span></div></div><div className="hero-visual"><img src="/assets/agcloud-banner.png"/><div className="floating-card one"><Zap/> Low Ping</div><div className="floating-card two"><ShieldCheck/> Anti-DDoS</div></div></div></section>
 <section className="section"><div className="container"><div className="section-heading"><span>Why AG Cloud</span><h2>Everything you need to host with confidence</h2></div><div className="feature-grid">{[[Server,'Modern infrastructure','NVMe storage and carefully selected compute for smooth workloads.'],[Gauge,'Optimized performance','High-speed network routes tuned for India and Asia.'],[ShieldCheck,'DDoS protection','Protection designed to keep your services reachable.'],[Headphones,'Human support','Get real help through our support channels when you need it.'],[LockKeyhole,'Secure accounts','Google sign-in, private order history and protected data.'],[Sparkles,'Premium experience','Clean client dashboard, clear plans and a fast purchase flow.']].map(([I,t,d]:any)=><article className="feature-card" key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="section dark-strip"><div className="container stats"><div><strong>99.9%</strong><span>Target uptime</span></div><div><strong>24/7</strong><span>Runtime</span></div><div><strong>1 Gbps</strong><span>VPS network</span></div><div><strong>10+</strong><span>Plan categories</span></div></div></section>
 <section className="section"><div className="container cta"><div><span className="eyebrow">Ready to launch?</span><h2>Pick your plan and start building.</h2></div><Link className="primary-btn" to="/plans">View all plans <ArrowRight size={18}/></Link></div></section>
 </>}
